name: Rory 
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home: /
  About: /about
  Archives: /archives
  # Impressum: 
  GitHub: https://github.com/roryye
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.png

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since: 2022
  name: Rory
  url: https://github.com/roryye
